### ISSUE TITLE
Tooltips in multiplayer not working correctly part#2

### ISSUE THREAD

**Issue by AnimusOccisor** [McJtyMods/FancyTrinkets#6] opened 2023-04-09 19:55 UTC
related https://github.com/McJtyMods/FancyTrinkets/issues/5#issuecomment-1499391515

Tried the update fancytrinkets-1.19-2.1.3 on the server.

Already made rings, no tooltips.

Just made a new ring .. also no tooltip. (damn, can not add picures) 

posted a picture on twatter

**Comment by McJty** [comment] 2023-04-10 04:52
Well that's normal. What tooltip are you expecting there?

**Comment by AnimusOccisor** [comment] 2023-04-10 18:50
More like in single player. And to clarify, the ring picture on twitter was one with XP and the ingredients to make a fire-resistant ring. Also JEI shows different info depending on multiplayer or single player.  In multiplayer only the base ring is shown and in single player it shows the recipes for the rings. Going to post the pictures for you on twitter again.

**Comment by McJty** [comment] 2023-04-11 03:36
At this moment I cannot reproduce any problem when I test on a server. So I need more info and the exact steps that you do

**Comment by AnimusOccisor** [comment] 2023-04-11 06:42
My own mod collection selected true the curseforge launcher and made a pack. No custom configs only current change is an increase in the amount of force loadable chunks true FTB
https://www.curseforge.com/minecraft/modpacks/minecolonies-tech-pack

Need to upload the current testbuild to there did not had the time yet.
Updated to the latest version form curseforge:

fancytrinkets-1.19-2.1.3.jar
curios-forge-1.19.2-5.1.3.0.jar
mcjtylib-1.19-7.2.2.jar And see there is an update for that again now.
theoneprobe-1.19-6.2.2.jar

So if the fix was in the libfile then we have the culprit. Might be able to test that somewhere today But kina have to work :x So tonight

**Comment by AnimusOccisor** [comment] 2023-04-12 07:16
Just did a short test, again created the fire ring, and no tooltip what so ever! After updating all your mods to the latest versions, that is.

**Comment by McJty** [comment] 2023-04-12 11:27
Can  you show me some screenshots on how you are creating the fire ring? Maybe a video?

**Comment by AnimusOccisor** [comment] 2023-04-12 17:12
That was some time ago i did stuff like this. ok, made a capture, compressed it and posted it on twitter

**Comment by McJty** [comment] 2023-04-13 03:01
I see nothing on twitter?

**Comment by McJty** [comment] 2023-04-13 04:01
Never mind, I managed to reproduce some weird behaviour. I'll investigate

**Comment by AnimusOccisor** [comment] 2023-04-13 04:39
pic.twitter.com/U8tVqe8BqM else like this ?

**Comment by McJty** [comment] 2023-04-13 04:47
It says that tweet is not available

**Comment by McJty** [comment] 2023-04-13 09:05
I think I fixed the bug. Will make a release later

**Comment by McJty** [comment] 2023-04-13 09:41
Fixed with latest version of McJtyLib (7.2.4). FancyTrinkets doesn't need an update

**Comment by AnimusOccisor** [comment] 2023-04-13 18:22
Just reposted the vid on twitter again. https://twitter.com/AnimusOccisor/status/1646579143222460422 No clue what went wrong before. Hope the new lib file resolves this, else we get a part3 :x

**Comment by McJty** [comment] 2023-04-14 08:13
Ok, it is not fixed. The reason I thought it was fixed was because if you first open a single player world and THEN go to a server then it will be fine on the server too. But not if you directly go to the server

**Comment by McJty** [comment] 2023-04-14 09:22
Just released a new version of Fancy Trinkets. Can you try again?

**Comment by AnimusOccisor** [comment] 2023-04-14 10:16
Only see a fancy trinkets update, stopping the server and updating .. back in a few.

**Comment by AnimusOccisor** [comment] 2023-04-14 10:25
Fixed *\o/* See also twitter :)

**Closed as completed** 2023-04-15 05:34 UTC
